[package]
name = "fork-cracker"
version = "5.26.3"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
crossterm = "0.25"
chrono = "0.4"

[[bin]]
name = "fork-cracker"
path = "main.rs"
